# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  test:
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            pip install -e .[dev]
      - run:
          command: pipdeptree
      - run:
          name: tests & coverage
          command: |
            pytest tests/ -s --cov --cov-report xml:test-reports/coverage.xml --junitxml test-reports/pytest/tests.xml
            coverage report -m
            bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          # must be a directory with named subdirectories
          path: test-reports

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              image: ["circleci/python:3.8.9", "circleci/python:3.9.9", "circleci/python:3.10.1"]
