# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  test:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt
            pip install -e .[dev]
      - run:
          command: pipdeptree
      - run:
          command: black . --check
      - run:
          command: isort . --check
      - run:
          # dont want to enforce typing on tests
          command: mypy --strict puretabix
      - run:
          name: tests & coverage
          command: |
            pytest tests/ -s --cov --cov-report xml:test-reports/coverage.xml --junitxml test-reports/pytest/tests.xml
            coverage report -m
            if [[ "<< parameters.image >>" == "circleci/python:3.8.9" ]] ; then bash <(curl -s https://codecov.io/bash) ; fi
      - store_test_results:
          # must be a directory with named subdirectories
          path: test-reports

workflows:
  tests:
    jobs:
      - test:
          matrix:
            parameters:
              image:
                [
                  "cimg/python:3.8.18",
                  "cimg/python:3.9.18",
                  "cimg/python:3.10.13",
                  "cimg/python:3.11.6",
                ]
